### ISSUE TITLE
Invalid W3 validation

### ISSUE THREAD

**Issue by VlMv** [qvarts/gulp-webp-retina-html#1]
Hey. I got a trouble with W3 validator. 
If I wanna use retina+webp, the plugin adds two versions of a 1x webp image (with retina suffix and without).
I suppose it works even so, but W3 validator shows that like an error.
I'm still learning HTML and CSS and my JS is about "burger like" coding. I can't fix that by myself.

If that's not the validator bug or a casual problem, it would be great the error is fixed.

> Error: Bad value **img/fat-cat.webp**, **img/fat-cat.webp 1x**, img/fat-cat@2x.webp 2x for attribute srcset on element [source](https://html.spec.whatwg.org/multipage/#the-source-element): Density for image img/fat-cat.webp is identical to density for image img/fat-cat.webp.

From line 135, column 22; to line 135, column 118

          <source srcset="img/fat-cat.webp, img/fat-cat.webp 1x, img/fat-cat@2x.webp 2x" type="image/webp">↩

**Comment by qvarts** [comment]
Hey @VlMv, I've added a [fix](https://github.com/qvarts/gulp-webp-retina-html/tree/1-invalid-w3-validation) for your problem. Check it out, please.

**Comment by VlMv** [comment]
Thank you
